# Generated by Django 3.0.5 on 2022-02-20 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20220212_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.CharField(default='Wario Wario', max_length=255),
        ),
    ]
