# Generated by Django 3.0.5 on 2022-02-20 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20220220_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(default='Abdirahman Wako', max_length=255),
        ),
    ]
